// NFL Quarterbacks for 2025 season with verified ESPN Player IDs
// ESPN headshot URL: https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/{espnId}.png

export const startingQBs = [
  { name: "Aaron Rodgers", team: "Pittsburgh Steelers", espn_id: "8439" },
  { name: "Baker Mayfield", team: "Tampa Bay Buccaneers", espn_id: "3052587" },
  { name: "Bo Nix", team: "Denver Broncos", espn_id: "4426338" },
  { name: "Brock Purdy", team: "San Francisco 49ers", espn_id: "4361741" },
  { name: "Bryce Young", team: "Carolina Panthers", espn_id: "4685720" },
  { name: "C.J. Stroud", team: "Houston Texans", espn_id: "4432577" },
  { name: "Caleb Williams", team: "Chicago Bears", espn_id: "4431611" },
  { name: "Cam Ward", team: "Tennessee Titans", espn_id: "4688380" },
  { name: "Dak Prescott", team: "Dallas Cowboys", espn_id: "2577417" },
  { name: "Daniel Jones", team: "Indianapolis Colts", espn_id: "3917792" },
  { name: "Drake Maye", team: "New England Patriots", espn_id: "4431452" },
  { name: "Geno Smith", team: "Las Vegas Raiders", espn_id: "15864" },
  { name: "J.J. McCarthy", team: "Minnesota Vikings", espn_id: "4433970" },
  { name: "Jalen Hurts", team: "Philadelphia Eagles", espn_id: "4040715" },
  { name: "Jared Goff", team: "Detroit Lions", espn_id: "3046779" },
  { name: "Jaxson Dart", team: "New York Giants", espn_id: "4689114" },
  { name: "Jayden Daniels", team: "Washington Commanders", espn_id: "4426348" },
  { name: "Joe Burrow", team: "Cincinnati Bengals", espn_id: "3915511" },
  { name: "Joe Flacco", team: "Cincinnati Bengals", espn_id: "11252" },
  { name: "Jordan Love", team: "Green Bay Packers", espn_id: "4036378" },
  { name: "Josh Allen", team: "Buffalo Bills", espn_id: "3918298" },
  { name: "Justin Fields", team: "New York Jets", espn_id: "4362887" },
  { name: "Justin Herbert", team: "Los Angeles Chargers", espn_id: "4038941" },
  { name: "Kirk Cousins", team: "Atlanta Falcons", espn_id: "14880" },
  { name: "Kyler Murray", team: "Arizona Cardinals", espn_id: "3917315" },
  { name: "Lamar Jackson", team: "Baltimore Ravens", espn_id: "3916387" },
  { name: "Mac Jones", team: "San Francisco 49ers", espn_id: "4241464" },
  { name: "Malik Willis", team: "Green Bay Packers", espn_id: "4242512" },
  { name: "Marcus Mariota", team: "Washington Commanders", espn_id: "2576980" },
  { name: "Matthew Stafford", team: "Los Angeles Rams", espn_id: "12483" },
  { name: "Michael Penix Jr.", team: "Atlanta Falcons", espn_id: "4360423" },
  { name: "Patrick Mahomes", team: "Kansas City Chiefs", espn_id: "3139477" },
  { name: "Sam Darnold", team: "Seattle Seahawks", espn_id: "3912547" },
  { name: "Shedeur Sanders", team: "Cleveland Browns", espn_id: "4432762" },
  { name: "Spencer Rattler", team: "New Orleans Saints", espn_id: "4426339" },
  { name: "Trevor Lawrence", team: "Jacksonville Jaguars", espn_id: "4360310" },
  { name: "Tua Tagovailoa", team: "Miami Dolphins", espn_id: "4241479" },
  { name: "Tyler Shough", team: "New Orleans Saints", espn_id: "4360689" },
];
